### ISSUE TITLE
10's coming out as 10's without suit

### ISSUE THREAD

**Issue by terhoraj** [goldfire/pokersolver#12]
I hope I am not doing anything wrong here but looks like all 10's comes out without suit when I use poker solver solve method and return cards from that object. Everything else works, see example picture:

![image](https://user-images.githubusercontent.com/19226200/34469371-27a78bec-ef26-11e7-94b8-ec022291e068.png)

this should have come out as 10h, 10s

**Comment by goldfire** [comment]
What data are you passing into the solve method?

**Comment by terhoraj** [comment]
Oh crap I feel so idiot. I passed in 10h for example not as Th

![image](https://user-images.githubusercontent.com/19226200/34491330-ab63555e-efeb-11e7-80e2-3f5f2865a4b2.png)

**Comment by goldfire** [comment]
Not a problem! I need to update the docs to make that more clear.
