### ISSUE TITLE
isPossible === true with duplicate cards

### ISSUE THREAD

**Issue by fvilers** [goldfire/pokersolver#14]
Hi, I'm poking around with the library and making a few tests before using it. If I solve a handle with two duplicate cards (Queen of diamond for example) the returning structure still has a `isPossible` flag to true. Shouldn't it be false?

**Comment by goldfire** [comment]
The library assumes that a valid deck has been used, so there aren't any checks for something like that at the moment.

**Comment by fvilers** [comment]
OK, I undestand. But what's the purpose of the `isPossible` flag then?

**Comment by goldfire** [comment]
It is really just an internal variable that could probably be named better to check if a hand type should be solved for (this is why it isn't listed in the docs).
