### ISSUE TITLE
Using kickers in combinations

### ISSUE THREAD

**Issue by EugeneButusov** [goldfire/pokersolver#16]
First of all, thank you for making this useful module.
I'm working with this product and found some interesting point:
 - Desk has `9c Kh Kd 9s Ah`
 - First user has `Qc 5h`
 - Second user has `5d Jd`

Library returns two winners, but as we can assume, due to kicker, winner is 1st player. Is it possible to distinguish somehow community cards or hand cards to make correct output for `Hand.winners` method?
Thanks in advance!

**Comment by ericblade** [comment]
This is a chop -- both players have KK99A, the Q does not play.

**Comment by EugeneButusov** [comment]
@ericblade, thanks, you're right, my bad with game rules understanding.
